### ISSUE TITLE
Tópico 01

### ISSUE THREAD

**Issue by jamilssj** [plinioleitao/sgbd-2023-2-bcc#19]
< escreva aqui a sua dúvida em detalhes >
Meu registro acadêmico: 20208062
Meu repositório no GitHub: https://github.com/jamilssj/sgbd-2023-2-bcc
Minhas expectativas com respeito à disciplina: arofundar conhecimentos apresentados ela disciplina.

**Comment by plinioleitao** [comment]
Obrigado!
